repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.6.3
    hooks:
      - id: conventional-commits

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]

  - repo: https://github.com/srstevenson/nb-clean
    rev: 2.4.0
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          - --preserve-cell-outputs
          - --preserve-cell-metadata
          - lines_to_next_cell
          - --

  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.5
    hooks:
      - id: jupytext
        args:
          - --sync
          - --pipe
          - "black - --config=pyproject.toml"
          - --pipe
          - "isort - --settings-path=pyproject.toml"
          - --pipe
          - "pycln - --config=pyproject.toml"
        additional_dependencies:
          - black==23.3.0
          - isort==5.12.0
          - pycln==2.1.3
