c:\users\admini~1\appdata\local\temp\零件1-熱 1
c:\users\admini~1\appdata\local\temp\零件1-熱 1
C:\Users\Administrator\Desktop\HT FINAL\uniform_circle-熱 1
C:\Users\Administrator\Desktop\HT FINAL\uniform_circle-熱 1
C:\Users\Administrator\Desktop\HT FINAL\uniform_circle-熱 1
C:\Users\Administrator\Desktop\HT FINAL\uniform_circle-熱 1
C:\Users\Administrator\Desktop\HT FINAL\uniform_circle-熱 1
C:\Users\Administrator\Desktop\HT FINAL\uniform_circle-熱 1
C:\Users\Administrator\Desktop\HT FINAL\linear_circle-熱 1
